### PR TITLE
Missing Section Error Messages (Repair & Salvage Config)

### LINKED ISSUE #4077: Repair Config NPE
Repair allows for custom configs (repair.*.yml) to be loaded

Currently, if you omit the Repairables section (required for mcMMO to load the file and repairables), it throws a NPE rather than warning the user that mcMMO couldn't find the Repairables section and to double-check their YML

This is confusing for users who don't understand how to read a stack trace or even realize mcMMO is opensource

Alternative: Catch the NPE and send a console warning that anyone can use to fix the issue

### PR DESCRIPTION
**Pull request by Ineusia**
Resolves #4077 and removes the same issue for Salvage

### CODE REVIEW

File: src/main/java/com/gmail/nossr50/config/skills/repair/RepairConfig.java [hunk 1]
```diff
@@ -26,7 +27,13 @@ public RepairConfig(String fileName) {
     protected void loadKeys() {
         repairables = new ArrayList<Repairable>();
 
+        if (!config.isConfigurationSection("Repairables")) {
+            mcMMO.p.getLogger().severe("Could not find Repairables section in " + fileName);
+            return;
+        }
+
         ConfigurationSection section = config.getConfigurationSection("Repairables");
+
```
Comment (Ineusia) [inline src/main/java/com/gmail/nossr50/config/skills/repair/RepairConfig.java]: This line add was purely reflex, didn't even realize I'd done it

File: src/main/java/com/gmail/nossr50/config/skills/repair/RepairConfig.java [hunk 2]
```diff
@@ -26,6 +27,11 @@ public RepairConfig(String fileName) {
     protected void loadKeys() {
         repairables = new ArrayList<Repairable>();
 
+        if (!config.isConfigurationSection("Repairables")) {
+            mcMMO.p.getLogger().severe("Could not find Repairables section in " + fileName);
+            return;
+        }
+
```
Comment (nossr50) [inline src/main/java/com/gmail/nossr50/config/skills/repair/RepairConfig.java]: Technically for a micro-optimization you could move this above the creation of the empty array list object

File: src/main/java/com/gmail/nossr50/config/skills/salvage/SalvageConfig.java [hunk 3]
```diff
@@ -27,6 +28,11 @@ public SalvageConfig(String fileName) {
     protected void loadKeys() {
         salvageables = new ArrayList<Salvageable>();
 
+        if (!config.isConfigurationSection("Salvageables")) {
+            mcMMO.p.getLogger().severe("Could not find Salvageables section in " + fileName);
+            return;
+        }
+
```
Comment (nossr50) [inline src/main/java/com/gmail/nossr50/config/skills/salvage/SalvageConfig.java]: Technically for a micro-optimization you could move this above the creation of the empty array list object
